name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distro: humble
      - name: build and test
        run: |
          source /opt/ros/humble/setup.bash
          # GitHub上のファイルを ~/ros2_ws/src/pomodoro_timer に配置
          mkdir -p ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE ~/ros2_ws/src/pomodoro_timer
          cd ~/ros2_ws
          # ビルド
          colcon build
          # テスト実行（フルパスで指定）
          bash ~/ros2_ws/src/pomodoro_timer/test.bash
