name: test
on: push

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: ros-tooling/setup-ros@v0.7
        with:
          # ここを 'required-ros-distro' から 'ros-distro' に修正しました
          ros-distro: humble
      - name: build and test
        run: |
          source /opt/ros/humble/setup.bash
          # フォルダ構成をGitHub上で再現
          mkdir -p ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE ~/ros2_ws/src/pomodoro_timer
          cd ~/ros2_ws
          colcon build
          # テスト実行
          bash ~/ros2_ws/src/pomodoro_timer/test.bash
